journal:
  identifiers:
    - systemd
    - kernel
    - systemd-oomd
  units:
    - systemd-networkd.service
    - systemd-resolved.service
    - systemd-logind.service
    - systemd
crash_paths:
  - /var/crash

